### ISSUE TITLE
Не загружается node

### ISSUE THREAD

**Issue by ElinaHaf** [ElinaHaf/DiplomProject#1]
## Описание

При запуске контейнеров из файла docker-compose.yml командой в терминале docker-compose up выходит ошибка

## Локация дефекта

Dockerfile

## Шаги воспроизведения
Открыть [код программы](https://github.com/ElinaHaf/DiplomProject.git) в IDEA
В терминале из файла docker-compose.yml прописать команду: docker-compose up
Ожидаемый результат: три контейнера запустились;
Фактический результат: два контейнера запустились, node не запустился

## Скриншот

![Ошибка](https://user-images.githubusercontent.com/103569727/206429650-5a496be5-3a74-4013-9a84-72d618659c24.jpg)

## Окружение
Операционная система Windows 11 Pro
IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
Java: 11.0.14.1+1-b2043.45 amd64, junit-jupiter

**Comment by ArRomanov** [comment]
Замените содержимое вашего Dockerfile на такое же, как тут - https://github.com/netology-code/aqa-code/blob/master/docker/node/Dockerfile

**Comment by ElinaHaf** [comment]
Заменила Dockerfile, при команде docker-compose up выходит следующая ошибка
![не работает](https://user-images.githubusercontent.com/103569727/207109316-b41923eb-1299-4d85-aea7-0fe7bc895c5c.jpg)

Также при загрузке node/app ошибка, что файл Dockerfile не найден, повторяется:
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount466100014/Dockerfile: no such file or directory

**Comment by ArRomanov** [comment]
попробуйте так
1. Остановить и удалить все контейнеры `docker-compose down`
2. Заменить содержимое docker-compose.yml на то, что приложу ниже
3. Перезапустить контейнеры командой `docker-compose up -d --force-recreate --build`
4. Если ничего не получится, то напишите мне в дискорд, мы решим с вами проблему вместе

```
version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node-app:
    build: gate-simulator
    ports:
      - '9999:9999'
```
